name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install packages
        run: npm install
      - name: Run linters
        run: npm run lint
